### ISSUE TITLE
Examples links vorbis, flac and opus but they're not used

### ISSUE THREAD

**Issue by diizzyy** [libsndfile/libsamplerate#146] opened 2021-01-28 02:39 UTC
From what I can tell these libraries aren't used at all but gets linked and are required via ```cmake/FindSndFile.cmake```.

**Comment by evpobr** [comment] 2021-02-08 06:12
Hi @diizzyy

Do use use latest version of libsndfile? It was fixed in latest release, all these external libraries are not required if shared (DLL) libsndfile library was found.

**Comment by diizzyy** [comment] 2021-02-10 13:27
Hi @evpobr 

When using 0.2.1 (release)

```
-- Found SndFile: /usr/local/lib/libsndfile.so (found version "1.0.30")
....
```

```
readelf -d work/.build/examples/timewarp-file

Dynamic section at offset 0x1900 contains 32 entries:
  Tag                Type                  Name/Value
 0x000000000000001d RUNPATH              Library runpath: [/usr/ports/audio/libsamplerate/work/.build/src:/usr/local/lib]
 0x0000000000000001 NEEDED               Shared library: [libm.so.5]
 0x0000000000000001 NEEDED               Shared library: [libsamplerate.so.0]
 0x0000000000000001 NEEDED               Shared library: [libsndfile.so.1]
 0x0000000000000001 NEEDED               Shared library: [libvorbisenc.so.2]
 0x0000000000000001 NEEDED               Shared library: [libvorbis.so.0]
 0x0000000000000001 NEEDED               Shared library: [libopus.so.0]
 0x0000000000000001 NEEDED               Shared library: [libFLAC.so.8]
 0x0000000000000001 NEEDED               Shared library: [libogg.so.0]
 0x0000000000000001 NEEDED               Shared library: [libc.so.7]
```

Perhaps I'm missing something?

**Comment by evpobr** [comment] 2021-02-10 16:06
Yes, overlinking does take place. So far I can't figure out if it's possible to avoid this when using the find module or if it's CMake's fee for cross-platform.

**Comment by diizzyy** [comment] 2021-02-10 16:49
I guess it comes from https://github.com/libsndfile/libsamplerate/blob/master/cmake/FindSndFile.cmake#L45 and https://github.com/libsndfile/libsamplerate/blob/master/cmake/FindSndFile.cmake#L46 ?

**Comment by evpobr** [comment] 2021-02-10 16:59
The problem is here:

https://github.com/libsndfile/libsamplerate/blob/7a42f1823814b5ec04fbc62206eaa83671458f36/cmake/FindSndFile.cmake#L53

**Comment by diizzyy** [comment] 2021-05-20 10:46
What would be the downside of just ripping it out?
https://github.com/freebsd/freebsd-ports/blob/main/audio/libsndfile/files/extrapatch-cmake_SndFileChecks.cmake-disableexternallibs

**Comment by diizzyy** [comment] 2021-05-20 10:49
What would be the downside of just removing it?
https://github.com/freebsd/freebsd-ports/blob/main/audio/libsamplerate/files/patch-cmake_FindSndFile.cmake

**Comment by evpobr** [comment] 2021-05-21 05:52
Static libsndfile linking will fail. This is common scenario on Windows.

**Comment by evpobr** [comment] 2021-05-21 06:43
@diizzyy , please test pull request.

**Comment by diizzyy** [comment] 2021-05-23 07:40
@evpobr 
Hi, that seems to work on my end at least! Thanks!

**Comment by evpobr** [comment] 2021-05-23 08:25
Thanks @diizzyy !

**Closed** 2021-05-23 08:24 UTC
Labels: bug
